sudo: required
services:
  - docker

before_install:
  - docker build -t immigration9/docker-react -f Dockerfile.dev .

script:
  - docker run immigration9/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-878265607169"
  bucket_path: "docker-react" # same as app name
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
